# http://doc.rultor.com/basics.html
docker:
  image: "mostalive/ubuntu-14.04-oracle-jdk8"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  commanders:
    - aistomin
  script: |-
    java --version
    mvn --version
    mvn clean install -Pqulice
